class Matn {
  String matn;

  Matn(this.matn);
}

class MatnServise {
  List<Matn> uzunMatn = [
    Matn(
        "Kompaniyani italiyalik Ferruccio Lamborghini 1963-yilda Ferrari kabi taniqli brendlar takliflari bilan raqobatlasha oladigan sayyohlik avtomobillarini ishlab chiqarish maqsadida asos solgan. Kompaniyaning 350 GT kabi birinchi modellari 1960-yillarning oʻrtalarida chiqarilgan. Lamborghini 1966-yilgi Miura sport kupesi uchun eʼtiborga sazovor boʻldi, u orqa dvigatelli, orqa gʻildirakli haydovchi sxemasidan foydalangan. Lamborghini oʻzining birinchi oʻn yilida tez oʻsdi, ammo 1973-yilgi global moliyaviy inqiroz va neft inqirozi ortidan sotuvlar pasaydi. Ferruccio Lamborghini kompaniyani Georges-Henri Rossetti va Rene Leimerga sotdi va 1974-yilda nafaqaga chiqdi. Kompaniya 1978-yilda bankrot boʻldi va 1980-yilda aka-uka Jan-Klod va Patrik Mimranlarning qabulxonasiga oʻtkazildi. Mimranlar kompaniyani qabul qilish huquqidan tashqarida sotib oldilar. 1984-yilga kelib uning kengayishiga katta sarmoya kiritdi. Mimrans boshqaruvi ostida Lamborghini modellari qatori Countachdan Jalpa sportkari va LM002 yuqori unumdor yoʻltanlamas avtomobilini oʻz ichiga olgan holda kengaytirildi. Mimranlar Lamborghini-ni 1987-yilda Chrysler korporatsiyasiga sotdilar. Chrysler Lamborghini-ni Malayziyaning Mycom Setdco investitsiya guruhiga va Indoneziyaning V’Power Corporation guruhiga, 1999-yilda Mycomco korporatsiyasiga sotdi. va V’Power Lamborghini-ni Volkswagen guruhiga sotdi, u yerda u guruhning Audi boʻlinmasi nazorati ostida edi. Brend portfeliga yangi mahsulotlar va model liniyalari kiritildi va bozorga olib kirildi. 2000-yillarning oxirlarida, butun jahon moliyaviy inqirozi davridava keyingi iqtisodiy inqiroz, Lamborghini sotuvi deyarli 50 foizga qisqardi.2021-yilda Lamborghini bosh direktori 2024-yilga kelib uning barcha modellari gibrid boʻlishini aytdi. "),
    Matn(
        "Mercedes-Benz 1886-yili asos solingan. Tashkilotchilar Karl Bents, Gotlib Daymler, Vilgelm Maybax. Joylashuvi: Shtutgart, Germaniya. Mahsuloti:Yengil avtomobillar, yuk tashuvchi avtomobillar, avtobuslar, dvigatellar. Web sahifasi: mercedes-benz.de Uning brendi 2010-yil 25,2 mlrd Aqsh Dollari deb belgilangan. U Yengil avtomobillar brend narxi boʻyicha 2-oʻrinni band etib turibdi.(2010). 2021-yil mart oyida «Mercedes-Benz» Xitoy bozoridan 2,6 million avtomobilni qaytarib olishga qaror qildi. Qaror ushbu mamlakatda ishlab chiqarilib, import qilingan avtomobillarga ham, modellarga ham tegishli boʻladi. Avtomobillarni qaytarib olishga ulardagi dasturiy taʼminot — favqulodda xizmatlarni chaqirish tizimida qayd etilgan muammo sabab boʻlgan. Nosozlik tufayli tizim avtohalokat sodir boʻlganidan keyin favqulodda xizmatlarga notoʻgʻri maʼlumotlar yuborgan va oqibatda qutqaruvchilar notoʻgʻri manzillarga borgan."),
    Matn(
        "Ferrari SpA (/ f ə ˈ r ɑːr i / italyancha:  [ferˈraːri]) — Italiyaning Maranello shahrida joylashgan hashamatli sport avtomobillari ishlab chiqaruvchi kompaniya. 1939-yilda Enzo Ferrari tomonidan Alfa Romeo poyga boʻlimidan Auto Avio Costruzioni nomi bilan asos solingan kompaniya hisoblanadi. Kompaniya 1940-yilda birinchi mashinasini ishlab chiqargan va 1947-yilda oʻzining birinchi Ferrari nishonli avtomobilini ommaga namoyish qilgan. 1969-yilda Ferrarining 50% ulushini sotib oldi va 1988-yilda oʻz ulushini 90% gacha kengaytirdi.  2014-yil oktabr oyida Fiat Chrysler Automobiles (FCA) Ferrari SpAʼni FCAʼdan ajratish niyatini eʼlon qildi. eʼlonga koʻra, FCA Ferrarining 90% ga egalik qiladi[1][2].  Ajralish 2015-yil oktabr oyida Ferrari NV ni (Niderlandiyada roʻyxatga olingan kompaniya) Ferrari SpA guruhining yangi xolding kompaniyasi sifatida tashkil etgan. Ajralishning qolgan bosqichlari orqali FCA ning Ferrari biznesidagi aktsiyalari FCA aktsiyadorlariga taqsimlandi, 10% esa Piero Ferrari ga tegishli boʻlishda davom etdi.  Spin-off 2016-yil 3-yanvarda yakunlandi."),
    Matn(
        "1909-yilda Ettore Bugatti oʻz kompaniyasiga asos soldi[2]. U zavod sifatida Molsemdagi tashlandiq bo'yoq zavodidan foydalangan. 1910-yilda paydo bo'lgan va 1911-yilda Ernest Fridrix boshqargan Fransiya Gran-prisida kuchli mashinalarni quvib o'tib, ikkinchi o'rinni egallagan[3]. Birinchi jahon urushidan keyin biroz o'zgartirilgan Type 13 1920-yilda Le Mans avtomobil kubogini qo'lga kiritdi. Type 13 asosida Bugatti Type 15, 17, 22 va 23 modellari yaratilgan bo'lib, ular turli shassi uzunliklarida farqlanadi. O'z davrining superkari Bugatti Type 18 1912-yilda taqdim etilgan. 100 litr hajmli dvigatel. bilan avtomobilni 160 km/soatgacha tezlashtirishi mumkin edi. Hammasi bo'lib 7 nusxa yaratilgan. 1923-yilda Tank laqabli Bugatti Type 32 yaratildi. Avtomobil poyga avtomobili dizaynida aerodinamikaga e'tibor qaratish nuqtai nazaridan juda yomon edi. 1924-yilda taqdim etilgan Bugatti Type 35 oʻz davrining eng muvaffaqiyatli poyga avtomobillaridan biriga aylandi, uning hisobida 2000 dan ortiq gʻalabalar[8]. Type 35 va uning modifikatsiyalari Ispaniya , Fransiya , Germaniya , Monako , Chexoslovakiya Gran-prilarida g'olib chiqdi."),
    Matn(
        "Chevrolet (SHEV-rə-LAY), (XFA ʃɛvrəˈleɪ) (AQSHda norasman Chevy deb ham ataladi[manba 501 kundan beri ko'rsatilmagan]) — iqtisodiy jihatdan mustaqil General Motors korporatsiyasi bo'linmasi tomonidan bir tovar belgisi ostida ishlab chiqariladigan va sotiladigan avtomobillar markasi. Chevrolet GM konserni markalari orasida eng mashhuri hisoblanadi: 2007 yilda 2,6 million dona avtomobil sotilgan[manba?]. Kompaniya 1911 yil 3-noyabrda Uilyam Dyurant tomonidan, shuningdek 1908 yilda General Motors kompaniyasiga asos solgan mashhur poygachi va avtomobil muhandisi Lui Chevrolet va sarmoyadorlar Uilyam Littl va Edvin Kempbell bilan birgalikda tashkil etilgan. Kompaniya oʻsha paytda Buick poyga jamoasida boʻlgan Lui Chevrolet sharafiga nomlangan. U Devid Buikning eng sevimli poygachisi edi. Logotipning paydo boʻlishining bir nechta variantlari mavjud. Eng mashhur va taniqlisi Parijga safari chogʻida Chevrolet asoschilaridan biri Uilyam Dyurant mehmonxonada qolib, devor qogʻozidagi qiziqarli rasmni qanday koʻrganligi haqida chiroyli hikoya edi. Dyurantga surat shu qadar yoqdiki, uyga qaytgach, uni kompaniya logotipi sifatida ishlatishni taklif qildi [manba?]."),
    Matn(
        "Ford Motor Company — jahondagi eng yirik avtomobil kompaniyalaridan biri. 1903-yilda AQSH avtomobil sanoati asoschilaridan biri, sanoatchi Genri Ford tomonidan tashkil etilgan. Boshkaruv idorasi Michigan shtatining Dirborn shahrida, eng katta zavodi Deytroyt shahrida joylashgan. Turli rusumdagi yengil, yuk avtomobillari, turli qishloq xoʻjaligi texnikasi (traktorlar) ishlab chiqaradi. F.M. dastavval ishni arzon avtomobillarni ishlab chiqarishdan boshladi. F.M. da jahonda birlamchi boʻlib avtomobillarni yigishda standartlashtirish va konveyer usuli qoʻllanildi. 8 soatlik ish vaqti joriy qilindi. F.M. 20-asrning 90-yillari oxiriga qadar yangi zavodlar qurish, boshqa avtomobil kompaniyalarini sotib olish hisobiga kengaydi. F.M. da avtomobillarning Ford, Lincoln, Mercury, Jaguar, Aston Martin, Mustang kabi 70 dan ortiq modellari yaratildi va ishlab chiqarildi. 1996-yilga kelib F.M. konveyeridan jami 250 million avtomobil chiqdi. 1998-yilda kompaniya yengil va yuk avtomobillari ishlab chiqarish hajmi boʻyicha jahonda 2oʻrinni egalladi. F.M. AQShdan tashqari dunyoning 30 mamlakatida oʻzining ishlab chiqarish, yigʻuv va savdo markazlariga, shuningdek, Mazda Motor, Kia Motors Corporation kompaniyalari aksiyalarida ulushga ega. Ford kompaniyasi yiliga 200 milliard dollr foyda topadi."),
   Matn("Ishlab chiqarish zavodi Karl Fridrix Rapp tomonidan 1916-yil oktabr oyida tashkil etilgan ammo, BMW 1917-yil 20-iyulda rasman ro'yxatdan o'tgan. Lekin dastlab Bayerische Flugzeug-Werke samalyotlari uchun dvigatellari ishlab chiqargan. Nemis samolyot ishlab chiqaruvchisi Gustav Otto tomonidanFlugmaschinenfabrik yaqinida BMW joylashganligi sababli uning dvigetillari tanlangan. 1916-yilda kompaniya Avstriya-Vengriya uchun V12 dvigatellarini ishlab chiqarish bo'yicha shartnoma imzoladi. Qo'shimcha mablag'ga muhtoj bo'lgan Rapp Camillo Castiglioni va Maks Fritzning sarmoya kiritish yordamini oladi, kompaniya Bayerische Motoren Werke GmbH degan nom bilan qayta tashkil etildi. 1917-yilda korxonaning tez o'sishiga ba'zi qiyinchiliklar sabab bo'ldi, shundan so'ng Rapp kompaniyani tark etdi, boshqaruv avstriyalik sanoatchi Frans Yozef Poppga o'tdi va 1918-yilda kompaniya nomi BMW AG deb qaytadan yana o'zgartirildi. 2007-yilda BMW konserni 1 203 482 dona avtomobil ishlab chiqargan (2006-yilning shu davriga nisbatan 7,6 foizga kamaydi). BMW 2020-yilda ishlab chiqarishni 25 foizga oshirish reja qilgan. Shunday qilib, 2016-yilda 2,4 million dona avtomobil ishlab chiqargan BMW 3,5 yil ichida kamida 3 million dona avtomobil ishlab chiqarishni rejalashtirgan[11].")
  ];

  Matn getUzunMatn(int index) {
    return uzunMatn[index];
  }
}
